# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('methodology', models.CharField(choices=[('activate', 'Activate'), ('agile', 'Agile'), ('waterfall', 'Waterfall'), ('hybrid', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('discovery', 'Discovery'), ('design', 'Design'), ('build', 'Build'), ('test', 'Test'), ('cutover', 'Cutover'), ('go_live', 'Go-Live'), ('hypercare', 'Hypercare'), ('closed', 'Closed')], default='not_started', max_length=20)),
                ('phase', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('assigned_pm_id', models.UUIDField(blank=True, null=True)),
                ('contracted_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('consumed_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cybercom_impl_project',
            },
        ),
        migrations.CreateModel(
            name='MethodologyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('methodology', models.CharField(choices=[('activate', 'Activate'), ('agile', 'Agile'), ('waterfall', 'Waterfall'), ('hybrid', 'Hybrid')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('phase_count', models.PositiveIntegerField(default=0)),
                ('task_templates', models.JSONField(default=list)),
                ('milestone_templates', models.JSONField(default=list)),
                ('estimated_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cybercom_impl_methodology_template',
            },
        ),
        migrations.CreateModel(
            name='HypercareLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('log_date', models.DateField()),
                ('issue_type', models.CharField(choices=[('bug', 'Bug'), ('question', 'Question'), ('training', 'Training'), ('performance', 'Performance'), ('data', 'Data')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_id', models.UUIDField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypercare_logs', to='cybercom_implementation.implementationproject')),
            ],
            options={
                'db_table': 'cybercom_impl_hypercare_log',
            },
        ),
        migrations.CreateModel(
            name='CutoverChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('checklist_name', models.CharField(max_length=200)),
                ('checklist_type', models.CharField(choices=[('pre_cutover', 'Pre-Cutover'), ('cutover_day', 'Cutover Day'), ('post_cutover', 'Post-Cutover'), ('go_live_verification', 'Go-Live Verification')], max_length=30)),
                ('items', models.JSONField(default=list)),
                ('completed_items', models.JSONField(default=list)),
                ('completed_by_id', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_checklists', to='cybercom_implementation.implementationproject')),
            ],
            options={
                'db_table': 'cybercom_impl_cutover_checklist',
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('milestone_name', models.CharField(max_length=200)),
                ('phase', models.CharField(blank=True, max_length=50)),
                ('target_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('deliverable_url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='cybercom_implementation.implementationproject')),
            ],
            options={
                'db_table': 'cybercom_impl_milestone',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_category', models.CharField(blank=True, max_length=100)),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cybercom_implementation.implementationproject')),
            ],
            options={
                'db_table': 'cybercom_impl_task',
            },
        ),
    ]
