# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(max_length=200)),
                ('role_type', models.CharField(choices=[('intern', 'Intern'), ('resident', 'Resident'), ('chief_resident', 'Chief Resident'), ('fellow', 'Fellow'), ('specialist', 'Specialist'), ('consultant', 'Consultant'), ('attending', 'Attending'), ('surgeon', 'Surgeon'), ('emergency_physician', 'Emergency Physician'), ('hospitalist', 'Hospitalist'), ('department_chair', 'Department Chair'), ('medical_director', 'Medical Director'), ('nurse_manager', 'Nurse Manager'), ('head_nurse', 'Head Nurse'), ('charge_nurse', 'Charge Nurse'), ('staff_nurse', 'Staff Nurse'), ('senior_nurse', 'Senior Nurse'), ('icu_nurse', 'ICU Nurse'), ('er_nurse', 'ER Nurse'), ('or_nurse', 'OR Nurse'), ('dialysis_nurse', 'Dialysis Nurse'), ('ld_nurse', 'Labor & Delivery Nurse'), ('pediatric_nurse', 'Pediatric Nurse'), ('nicu_nurse', 'NICU Nurse'), ('float_nurse', 'Float Nurse'), ('travel_nurse', 'Travel Nurse'), ('agency_nurse', 'Agency Nurse'), ('pharmacist', 'Pharmacist'), ('clinical_pharmacist', 'Clinical Pharmacist'), ('lab_technologist', 'Lab Technologist'), ('radiologic_technologist', 'Radiologic Technologist'), ('respiratory_therapist', 'Respiratory Therapist'), ('physical_therapist', 'Physical Therapist'), ('occupational_therapist', 'Occupational Therapist'), ('dialysis_technician', 'Dialysis Technician'), ('biomedical_engineer', 'Biomedical Engineer'), ('cssd_technician', 'CSSD Technician'), ('blood_bank_technologist', 'Blood Bank Technologist'), ('ward_clerk', 'Ward Clerk'), ('scheduler', 'Scheduler'), ('other', 'Other')], max_length=40)),
                ('clinical_category', models.CharField(choices=[('physician', 'Physician'), ('nursing', 'Nursing'), ('allied_health', 'Allied Health'), ('administrative', 'Administrative')], max_length=30)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('resident_training', 'Resident Training'), ('fellow_training', 'Fellow Training'), ('travel', 'Travel'), ('agency', 'Agency'), ('locum', 'Locum Tenens'), ('volunteer', 'Volunteer')], default='full_time', max_length=30)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('sub_specialty', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_float_eligible', models.BooleanField(default=False)),
                ('can_self_schedule', models.BooleanField(default=True)),
                ('identity_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_profiles_profile',
                'unique_together': {('tenant_id', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('credential_type', models.CharField(choices=[('medical_license', 'Medical License'), ('nursing_license', 'Nursing License'), ('board_certification', 'Board Certification'), ('bls', 'BLS'), ('acls', 'ACLS'), ('pals', 'PALS'), ('tncc', 'TNCC'), ('specialty_certification', 'Specialty Certification'), ('pacs_admin', 'PACS Administrator'), ('blood_bank_cert', 'Blood Bank Certification'), ('scrub_cert', 'Scrub/Circulating Certification'), ('other', 'Other')], max_length=40)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('credential_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending_renewal', 'Pending Renewal')], default='valid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='cymed_hwm_profiles.workforceprofile')),
            ],
            options={
                'db_table': 'cymed_hwm_profiles_credential',
            },
        ),
        migrations.CreateModel(
            name='CompetencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('competency_code', models.CharField(max_length=100)),
                ('competency_name', models.CharField(max_length=200)),
                ('certified_at', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('assessed_by_id', models.UUIDField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='cymed_hwm_profiles.workforceprofile')),
            ],
            options={
                'db_table': 'cymed_hwm_profiles_competency',
                'unique_together': {('tenant_id', 'profile', 'competency_code')},
            },
        ),
    ]
