# Generated by Django 6.0.6 on 2026-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_eligibility', '0002_rename_cymed_rcm_cov_ver_tenant_patient_idx_cymed_rcm_c_tenant__12412e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='nphies_bundle_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='nphies_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='nphies_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('offline', 'Offline (Queued for Retry)'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='eligibilityresponse',
            name='nphies_response_bundle_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
