# Generated by Django 6.0.6 on 2026-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_icu', '0001_initial'),
        ('cymed_hospital_inpatient', '0002_hospitalstay_current_code_status_codestatusorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustay',
            name='birth_weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icustay',
            name='gestational_age_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icustay',
            name='unit_type',
            field=models.CharField(choices=[('micu_sicu', 'Medical/Surgical ICU'), ('ccu', 'Coronary Care Unit (CCU)'), ('nicu', 'Neonatal ICU (NICU)'), ('picu', 'Pediatric ICU (PICU)')], default='micu_sicu', max_length=20),
        ),
        migrations.AddIndex(
            model_name='icustay',
            index=models.Index(fields=['tenant_id', 'unit_type'], name='cymed_hospi_tenant__9ce667_idx'),
        ),
    ]
