# Generated by Django 6.0.6 on 2026-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accommodation_tier',
            field=models.CharField(choices=[('multi_bed', 'Standard Multi-Bed'), ('single_bed', 'Standard Single-Bed'), ('vip', 'VIP')], default='multi_bed', help_text='Accommodation class for room-rate billing, independent of clinical room_type -- a VIP room is still room_type=standard clinically, but bills at the VIP tier.', max_length=30),
        ),
    ]
