# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('authorized_by_id', models.UUIDField(db_index=True)),
                ('authorized_by_role', models.CharField(max_length=100)),
                ('incident_id', models.CharField(db_index=True, max_length=200)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField()),
                ('affected_violations', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_hwm_fatigue_disaster_override',
            },
        ),
        migrations.CreateModel(
            name='DutyHourLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('roster_slot_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_resident', models.BooleanField(default=False)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('includes_handover', models.BooleanField(default=False)),
                ('facility_id', models.UUIDField(db_index=True)),
            ],
            options={
                'db_table': 'cymed_hwm_fatigue_duty_log',
            },
        ),
        migrations.CreateModel(
            name='FatigueViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('roster_slot_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('violation_type', models.CharField(choices=[('max_weekly_hours', 'Maximum Weekly Hours Exceeded'), ('max_consecutive_days', 'Maximum Consecutive Days Exceeded'), ('min_rest_period', 'Minimum Rest Period Violated'), ('max_shift_length', 'Maximum Shift Length Exceeded'), ('consecutive_night_cap', 'Consecutive Night Shifts Cap Exceeded'), ('acgme_80h_weekly', 'ACGME 80-Hour Weekly Cap'), ('acgme_max_shift_28h', 'ACGME 28-Hour Shift Limit'), ('acgme_rest_14h', 'ACGME 14-Hour Rest After 24h Shift'), ('acgme_call_frequency', 'ACGME 1-in-3 Call Frequency'), ('duty_hour_warning', 'Duty Hour Warning (75+ hours in 7 days)')], max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overridden', 'Override Approved'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('override_by_id', models.UUIDField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('prescribing_authority_revoked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hwm_fatigue_violation',
            },
        ),
        migrations.CreateModel(
            name='WeeklyHoursSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('week_start', models.DateField(db_index=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('night_shift_count', models.PositiveSmallIntegerField(default=0)),
                ('consecutive_days_worked', models.PositiveSmallIntegerField(default=0)),
                ('is_resident', models.BooleanField(default=False)),
                ('rolling_4wk_avg_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_fatigue_weekly_summary',
                'unique_together': {('tenant_id', 'workforce_profile_id', 'week_start')},
            },
        ),
    ]
