# Generated by Django 6.0.6 on 2026-07-11 21:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(help_text='e.g. "patient", "stock_item", "stock_batch".', max_length=100)),
                ('model_label', models.CharField(help_text='Django app_label.ModelName, e.g. "cymed_patients.Patient".', max_length=200)),
                ('object_id', models.UUIDField()),
                ('source_row_identifier', models.CharField(blank=True, help_text='Natural key from the source CSV row (MRN, SKU, etc.).', max_length=255)),
                ('imported_by_script', models.CharField(max_length=255)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_common_migration_records',
                'indexes': [models.Index(fields=['tenant_id', 'batch_id'], name='platform_co_tenant__d3d60e_idx'), models.Index(fields=['tenant_id', 'model_label', 'object_id'], name='platform_co_tenant__8ae537_idx')],
            },
        ),
    ]
