# Generated by Django 6.0.6 on 2026-07-08 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_hospital_inpatient', '0002_hospitalstay_current_code_status_codestatusorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortuaryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('time_of_death', models.DateTimeField()),
                ('pronounced_by', models.UUIDField()),
                ('cause_of_death_summary', models.TextField(blank=True)),
                ('refrigeration_bay', models.CharField(blank=True, max_length=50)),
                ('intake_at', models.DateTimeField(auto_now_add=True)),
                ('intake_by', models.UUIDField()),
                ('autopsy_required', models.BooleanField(default=False)),
                ('medical_examiner_case', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_refrigeration', 'In Refrigeration'), ('autopsy_pending', 'Autopsy Pending'), ('autopsy_complete', 'Autopsy Complete'), ('released', 'Released')], default='in_refrigeration', max_length=20)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortuary_case', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_mortuary_cases',
                'ordering': ['-intake_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('released_to_type', models.CharField(choices=[('family', 'Family Member'), ('funeral_home', 'Funeral Home'), ('medical_examiner', 'Medical Examiner'), ('organ_procurement', 'Organ Procurement Organization')], max_length=20)),
                ('released_to_name', models.CharField(max_length=200)),
                ('released_to_relationship', models.CharField(blank=True, max_length=100)),
                ('funeral_home_license_number', models.CharField(blank=True, max_length=100)),
                ('id_verified', models.BooleanField(default=False)),
                ('released_by', models.UUIDField()),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_records', to='cymed_hospital_mortuary.mortuarycase')),
            ],
            options={
                'db_table': 'cymed_hospital_mortuary_release_records',
                'ordering': ['-released_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mortuarycase',
            index=models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__da787c_idx'),
        ),
    ]
