# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallSLAMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('specialty', models.CharField(max_length=100)),
                ('metric_date', models.DateField(db_index=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('pages_within_sla', models.PositiveIntegerField(default=0)),
                ('pages_escalated', models.PositiveIntegerField(default=0)),
                ('avg_response_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sla_compliance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'cymed_hwm_analytics_oncall_sla',
            },
        ),
        migrations.CreateModel(
            name='WorkforceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('generated_by_id', models.UUIDField(db_index=True)),
                ('report_type', models.CharField(choices=[('staffing_coverage', 'Staffing Coverage Report'), ('fatigue_compliance', 'Fatigue & Duty Hour Compliance'), ('credential_expiry', 'Credential Expiry Report'), ('overtime_analysis', 'Overtime Analysis'), ('agency_utilization', 'Agency Staff Utilization'), ('float_pool_usage', 'Float Pool Usage'), ('acuity_trend', 'Patient Acuity Trend'), ('oncall_response', 'On-Call Response SLA Report'), ('roster_compliance', 'Roster Compliance Audit'), ('vacancy_rate', 'Shift Vacancy Rate')], max_length=40)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymed_hwm_analytics_report',
            },
        ),
        migrations.CreateModel(
            name='WorkforceAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=15)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_fte', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('avg_nurse_patient_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_compliance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('agency_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('float_deployments', models.PositiveIntegerField(default=0)),
                ('vacancy_shifts', models.PositiveIntegerField(default=0)),
                ('total_shifts', models.PositiveIntegerField(default=0)),
                ('vacancy_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fatigue_violations', models.PositiveIntegerField(default=0)),
                ('shortage_alerts', models.PositiveIntegerField(default=0)),
                ('avg_oncall_response_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_analytics_snapshot',
                'unique_together': {('tenant_id', 'facility_id', 'department_id', 'period_start', 'period_type')},
            },
        ),
    ]
