# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('financial', 'Financial'), ('operations', 'Operations'), ('clinical', 'Clinical'), ('hr', 'Human Resources')], max_length=30)),
                ('query_definition', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_bi_reports',
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('period', models.CharField(default='daily', max_length=50)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cycom_bi_dashboard_metrics',
            },
        ),
    ]
