# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RosterCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_by_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hwm_sched_roster_cycle',
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('shift_type', models.CharField(choices=[('8h_morning', '8-Hour Morning (07:00-15:00)'), ('8h_afternoon', '8-Hour Afternoon (15:00-23:00)'), ('8h_night', '8-Hour Night (23:00-07:00)'), ('12h_day', '12-Hour Day (07:00-19:00)'), ('12h_night', '12-Hour Night (19:00-07:00)'), ('fixed', 'Fixed'), ('rotating', 'Rotating'), ('on_call', 'On-Call'), ('research_block', 'Non-Clinical Research Block')], max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('handover_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_department_types', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cymed_hwm_sched_shift_template',
            },
        ),
        migrations.CreateModel(
            name='SelfScheduleWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('min_weekend_shifts', models.PositiveSmallIntegerField(default=2)),
                ('min_night_shifts', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('roster_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_schedule_window', to='cymed_hwm_scheduling.rostercycle')),
            ],
            options={
                'db_table': 'cymed_hwm_sched_self_schedule_window',
            },
        ),
        migrations.CreateModel(
            name='RosterSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('slot_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('swapped', 'Swapped'), ('absent', 'Absent')], default='scheduled', max_length=20)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_self_scheduled', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('roster_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cymed_hwm_scheduling.rostercycle')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='cymed_hwm_scheduling.shifttemplate')),
            ],
            options={
                'db_table': 'cymed_hwm_sched_roster_slot',
            },
        ),
        migrations.CreateModel(
            name='SlotQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('slot_date', models.DateField()),
                ('required_count', models.PositiveSmallIntegerField(default=1)),
                ('filled_count', models.PositiveSmallIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('roster_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_quotas', to='cymed_hwm_scheduling.rostercycle')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_quotas', to='cymed_hwm_scheduling.shifttemplate')),
            ],
            options={
                'db_table': 'cymed_hwm_sched_slot_quota',
            },
        ),
    ]
