# Generated by Django 6.0.6 on 2026-07-08 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaulerManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('manifest_number', models.CharField(max_length=100)),
                ('hauler_company', models.CharField(max_length=200)),
                ('hauler_license_number', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('waste_type', models.CharField(choices=[('general', 'General/Non-Hazardous'), ('biohazard', 'Biohazard (Red Bag)'), ('sharps', 'Sharps'), ('pharmaceutical', 'Pharmaceutical'), ('chemotherapy', 'Chemotherapy/Cytotoxic'), ('radioactive', 'Radioactive')], max_length=20)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disposal_facility', models.CharField(blank=True, max_length=200)),
                ('disposal_method', models.CharField(blank=True, max_length=100)),
                ('facility_representative_signed', models.BooleanField(default=False)),
                ('driver_signature_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('in_transit', 'In Transit'), ('disposed', 'Disposed / Confirmed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'cymed_hospital_waste_hauler_manifests',
                'ordering': ['-pickup_date'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__6de210_idx')],
                'unique_together': {('tenant_id', 'manifest_number')},
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('waste_type', models.CharField(choices=[('general', 'General/Non-Hazardous'), ('biohazard', 'Biohazard (Red Bag)'), ('sharps', 'Sharps'), ('pharmaceutical', 'Pharmaceutical'), ('chemotherapy', 'Chemotherapy/Cytotoxic'), ('radioactive', 'Radioactive')], max_length=20)),
                ('source_location', models.CharField(max_length=100)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('collected_by', models.UUIDField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('staged', 'Staged at Unit'), ('collected', 'Collected to Holding Depot'), ('awaiting_pickup', 'Awaiting Hauler Pickup'), ('picked_up', 'Picked Up by Hauler')], default='staged', max_length=20)),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_logs', to='cymed_hospital_waste_management.haulermanifest')),
            ],
            options={
                'db_table': 'cymed_hospital_waste_collection_logs',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['tenant_id', 'waste_type'], name='cymed_hospi_tenant__699b3c_idx'), models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__25f950_idx')],
            },
        ),
    ]
