# Generated by Django 6.0.6 on 2026-07-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='jofotara_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jofotara_invoice_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jofotara_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jofotara_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jofotara_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
