# Generated by Django 6.0.6 on 2026-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0002_invoice_jofotara_error_invoice_jofotara_invoice_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='zatca_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_cryptographic_stamp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_invoice_counter_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_invoice_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_previous_invoice_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
