# Generated by Django 6.0.6 on 2026-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0003_invoice_zatca_cleared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='external_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_source_system',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
