# Generated by Django 6.0.6 on 2026-07-07 19:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0004_invoice_external_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='jofotara_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_clearance', 'Pending Government Clearance'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zatca_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_clearance', 'Pending Government Clearance'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='OfflineTaxQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('provider_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('submitted', 'Submitted'), ('failed_permanent', 'Failed (Requires Review)')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_tax_queue_entries', to='cymed_rcm_billing.invoice')),
            ],
            options={
                'db_table': 'cymed_rcm_bill_offline_tax_queue',
                'ordering': ['queued_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='cymed_rcm_b_tenant__b68e4a_idx')],
            },
        ),
    ]
