# Generated by Django 6.0.6 on 2026-07-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0005_alter_invoice_jofotara_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='service_classification',
            field=models.CharField(choices=[('medical_necessity', 'Medical Necessity'), ('elective', 'Elective'), ('retail', 'Retail')], default='medical_necessity', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
