# Generated by Django 6.0.6 on 2026-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_billing', '0006_invoiceline_service_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_government_subsidy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='government_subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
