# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('census_date', models.DateField(db_index=True)),
                ('actual_census', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('er_visits', 'Emergency Room Visits'), ('inpatient_admissions', 'Inpatient Admissions'), ('outpatient_calendar', 'Outpatient Calendar'), ('surgical_schedule', 'Surgical Schedule'), ('historical_trend', 'Historical Trend')], max_length=30)),
            ],
            options={
                'db_table': 'cymed_hwm_forecast_census_point',
            },
        ),
        migrations.CreateModel(
            name='StaffingForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('forecast_date', models.DateField(db_index=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('applied', 'Applied to Roster'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('predicted_census', models.PositiveSmallIntegerField(default=0)),
                ('recommended_fte', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recommended_nurse_fte', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recommended_physician_fte', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('surge_predicted', models.BooleanField(default=False)),
                ('surge_reason', models.CharField(blank=True, max_length=200)),
                ('input_data_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cymed_hwm_forecast_staffing',
            },
        ),
        migrations.CreateModel(
            name='ForecastRosterMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('roster_cycle_id', models.UUIDField(db_index=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_mappings', to='cymed_hwm_forecasting.staffingforecast')),
            ],
            options={
                'db_table': 'cymed_hwm_forecast_roster_map',
            },
        ),
        migrations.CreateModel(
            name='ForecastAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('adjusted_by_id', models.UUIDField(db_index=True)),
                ('original_fte', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adjusted_fte', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='cymed_hwm_forecasting.staffingforecast')),
            ],
            options={
                'db_table': 'cymed_hwm_forecast_adjustment',
            },
        ),
    ]
