# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStaffRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('agency_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=100)),
                ('role_type', models.CharField(max_length=40)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('credential_verified', models.BooleanField(default=False)),
                ('credential_verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ehr_access_token_issued', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending_verification', max_length=30)),
            ],
            options={
                'db_table': 'cymed_hwm_float_pool_agency_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffingShortageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('roster_slot_id', models.UUIDField(db_index=True)),
                ('escalation_level', models.CharField(choices=[('level_0', 'Level 0 — Float Pool Available'), ('level_1', 'Level 1 — Head Nurse Notified'), ('level_2', 'Level 2 — Nurse Manager Notified'), ('level_3', 'Level 3 — Diversion / Admission Caps')], max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.CharField(blank=True, max_length=100)),
                ('diversion_activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hwm_float_pool_shortage_alert',
            },
        ),
        migrations.CreateModel(
            name='FloatPoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('eligible_department_ids', models.JSONField(default=list)),
                ('eligible_ward_types', models.JSONField(default=list)),
                ('priority_score', models.PositiveSmallIntegerField(default=50)),
                ('is_network_float', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hwm_float_pool_member',
                'unique_together': {('tenant_id', 'workforce_profile_id')},
            },
        ),
        migrations.CreateModel(
            name='FloatDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('target_department_id', models.UUIDField(db_index=True)),
                ('target_facility_id', models.UUIDField(db_index=True)),
                ('roster_slot_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('recalled', 'Recalled'), ('unavailable', 'Unavailable')], default='deployed', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('deployment_reason', models.TextField(blank=True)),
                ('float_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='cymed_hwm_float_pool.floatpoolmember')),
            ],
            options={
                'db_table': 'cymed_hwm_float_pool_deployment',
            },
        ),
    ]
