# Generated by Django 6.0.6 on 2026-07-05 23:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('requested_by', models.UUIDField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('justification', models.TextField(blank=True)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to PO')], default='draft', max_length=20)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('source_reorder_alert_id', models.UUIDField(blank=True, help_text='Set when this requisition was auto-generated from an inventory ReorderAlert.', null=True)),
                ('purchase_order_id', models.UUIDField(blank=True, help_text='Set once this requisition has been converted into a real PurchaseOrder.', null=True)),
            ],
            options={
                'db_table': 'cycom_procurement_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('stock_item_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cycom_procurement_requisitions.purchaserequisition')),
            ],
            options={
                'db_table': 'cycom_procurement_requisition_lines',
                'ordering': ['created_at'],
            },
        ),
    ]
