# Generated by Django 6.0.6 on 2026-07-08 09:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_hospital_inpatient', '0002_hospitalstay_current_code_status_codestatusorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandHygieneObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('unit', models.CharField(max_length=100)),
                ('observed_staff_id', models.UUIDField()),
                ('moment', models.CharField(choices=[('before_patient_contact', 'Before Patient Contact'), ('before_aseptic_procedure', 'Before Aseptic Procedure'), ('after_body_fluid_exposure', 'After Body Fluid Exposure Risk'), ('after_patient_contact', 'After Patient Contact'), ('after_patient_surroundings', 'After Touching Patient Surroundings')], max_length=30)),
                ('compliant', models.BooleanField()),
                ('observed_by', models.UUIDField()),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymed_hospital_infection_control_hand_hygiene',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['tenant_id', 'unit'], name='cymed_hospi_tenant__738f37_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutbreakInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('suspected_pathogen', models.CharField(blank=True, max_length=200)),
                ('unit_affected', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('contained', 'Contained'), ('closed', 'Closed')], default='investigating', max_length=20)),
                ('lead_investigator_id', models.UUIDField()),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hospital_infection_control_outbreaks',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__a7103d_idx')],
            },
        ),
        migrations.CreateModel(
            name='HAICase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('infection_site', models.CharField(choices=[('clabsi', 'Central Line-Associated Bloodstream Infection (CLABSI)'), ('cauti', 'Catheter-Associated Urinary Tract Infection (CAUTI)'), ('ssi', 'Surgical Site Infection (SSI)'), ('vap', 'Ventilator-Associated Pneumonia (VAP)'), ('c_diff', 'Clostridioides difficile Infection'), ('other', 'Other HAI')], max_length=20)),
                ('device_associated', models.BooleanField(default=False)),
                ('onset_date', models.DateField()),
                ('organism', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('confirmed', 'Confirmed'), ('ruled_out', 'Ruled Out'), ('resolved', 'Resolved')], default='suspected', max_length=20)),
                ('reported_by', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hai_cases', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_infection_control_hai_cases',
                'ordering': ['-onset_date'],
                'indexes': [models.Index(fields=['tenant_id', 'infection_site'], name='cymed_hospi_tenant__c5e50b_idx'), models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__bcac2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IsolationPrecaution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('precaution_type', models.CharField(choices=[('contact', 'Contact'), ('droplet', 'Droplet'), ('airborne', 'Airborne'), ('protective', 'Protective (Reverse) Isolation'), ('contact_enteric', 'Contact Enteric (C. diff)')], max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('ordered_by', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_precautions', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_infection_control_isolation',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant_id', 'ended_at'], name='cymed_hospi_tenant__e65050_idx')],
            },
        ),
    ]
