# Generated by Django 6.0.6 on 2026-07-05 22:09

import platform.common.security.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='value_string',
            field=platform.common.security.encryption.EncryptedTextField(blank=True),
        ),
    ]
