# Generated by Django 6.0.6 on 2026-07-07 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('incident_type', models.CharField(choices=[('medication_error', 'Medication Error'), ('fall', 'Patient Fall'), ('adverse_event', 'Adverse Event'), ('near_miss', 'Near Miss'), ('equipment_failure', 'Equipment Failure'), ('needlestick', 'Needlestick/Sharps Injury'), ('security', 'Security Incident'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('sentinel', 'Sentinel Event')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('reported_by', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed')], default='reported', max_length=30)),
            ],
            options={
                'db_table': 'cymed_hospital_incident_reports',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('analysis_text', models.TextField()),
                ('contributing_factors', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('conducted_by', models.UUIDField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_analysis', to='cymed_hospital_incident_reporting.incidentreport')),
            ],
            options={
                'db_table': 'cymed_hospital_incident_rca',
            },
        ),
    ]
