# Generated by Django 6.0.6 on 2026-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingorder',
            name='order_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('scheduled', 'Scheduled'), ('teleradiology', 'Teleradiology'), ('external', 'External Referral')], default='outpatient', max_length=30),
        ),
    ]
