# Generated by Django 6.0.6 on 2026-07-07 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0003_encrypt_existing_phi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('blood_type', models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=5)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('ineligibility_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hospital_blood_donors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('unit_number', models.CharField(max_length=100, unique=True)),
                ('blood_type', models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=5)),
                ('component_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('rbc', 'Packed Red Blood Cells'), ('plasma', 'Fresh Frozen Plasma'), ('platelets', 'Platelets'), ('cryoprecipitate', 'Cryoprecipitate')], default='whole_blood', max_length=30)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('discarded', 'Discarded'), ('quarantine', 'Quarantine')], default='quarantine', max_length=20)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='cymed_hospital_blood_bank.blooddonor')),
            ],
            options={
                'db_table': 'cymed_hospital_blood_units',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='CrossmatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('blood_type_required', models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=5)),
                ('units_requested', models.PositiveSmallIntegerField(default=1)),
                ('requested_by', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatch_requests', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_hospital_blood_crossmatch_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('issued_by', models.UUIDField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('blood_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_record', to='cymed_hospital_blood_bank.bloodunit')),
                ('crossmatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cymed_hospital_blood_bank.crossmatchrequest')),
            ],
            options={
                'db_table': 'cymed_hospital_blood_issues',
                'ordering': ['-issued_at'],
            },
        ),
    ]
