# Generated by Django 6.0.6 on 2026-07-07 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_blood_bank', '0001_initial'),
        ('cymed_patients', '0003_encrypt_existing_phi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='special_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='clinical_indication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='urgency',
            field=models.CharField(choices=[('elective', 'Elective'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('massive_hemorrhage_protocol', 'Massive Hemorrhage Protocol')], default='elective', max_length=30),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='component_type',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('rbc', 'Packed Red Blood Cells'), ('plasma', 'Fresh Frozen Plasma'), ('platelets', 'Platelets'), ('cryoprecipitate', 'Cryoprecipitate'), ('albumin', 'Albumin'), ('ivig', 'IVIG')], default='whole_blood', max_length=30),
        ),
        migrations.CreateModel(
            name='BloodCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('blood_type', models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=5)),
                ('antibody_screen', models.CharField(choices=[('not_done', 'Not Done'), ('negative', 'Negative'), ('positive', 'Positive'), ('positive_pending', 'Positive - Pending ID')], default='not_done', max_length=20)),
                ('antibodies_identified', models.JSONField(blank=True, default=list)),
                ('special_requirements', models.JSONField(blank=True, default=list)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sample_expiry_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_compatibility_records', to='cymed_patients.patient')),
            ],
            options={
                'verbose_name_plural': 'blood compatibility records',
                'db_table': 'cymed_hospital_blood_compatibility',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('reserved_units', models.PositiveIntegerField(default=0)),
                ('minimum_threshold', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('component_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('rbc', 'Packed Red Blood Cells'), ('plasma', 'Fresh Frozen Plasma'), ('platelets', 'Platelets'), ('cryoprecipitate', 'Cryoprecipitate'), ('albumin', 'Albumin'), ('ivig', 'IVIG')], default='whole_blood', max_length=30)),
                ('blood_type', models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=5)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'blood inventory',
                'db_table': 'cymed_hospital_blood_inventory',
                'ordering': ['component_type', 'blood_type'],
                'unique_together': {('tenant_id', 'component_type', 'blood_type', 'storage_location')},
            },
        ),
    ]
