# Generated by Django 6.0.6 on 2026-07-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_adt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreason',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissiontype',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargedisposition',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargereason',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='admissionreason',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_admission_reason_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='admissiontype',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_admission_type_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='dischargedisposition',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_discharge_disposition_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='dischargereason',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_discharge_reason_tenant_code'),
        ),
    ]
