# Generated by Django 6.0.6 on 2026-07-05 22:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_pharmacy_dispensing', '0001_initial'),
        ('cymed_pharmacy_prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('held', 'Held'), ('refused', 'Refused'), ('missed', 'Missed'), ('late', 'Given Late')], default='scheduled', max_length=20)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('administered_by', models.UUIDField(blank=True, help_text='Nurse/provider id', null=True)),
                ('dose_given', models.CharField(blank=True, max_length=100)),
                ('route_given', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('hold_reason', models.TextField(blank=True)),
                ('refused_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient_barcode_scanned', models.CharField(blank=True, max_length=255)),
                ('drug_barcode_scanned', models.CharField(blank=True, max_length=255)),
                ('barcode_match_verified', models.BooleanField(default=False)),
                ('barcode_override_reason', models.TextField(blank=True, help_text='Required if administered without a matching barcode scan.')),
                ('dispense_item', models.ForeignKey(blank=True, help_text='The specific dispensed unit this dose was drawn from, when known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='cymed_pharmacy_dispensing.dispenseitem')),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='cymed_pharmacy_prescriptions.medicationorder')),
            ],
            options={
                'db_table': 'cymed_pharmacy_mar',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['patient_id', 'scheduled_at'], name='cymed_pharm_patient_7259e2_idx'), models.Index(fields=['medication_order', 'status'], name='cymed_pharm_medicat_c0ed49_idx'), models.Index(fields=['tenant_id', 'status', 'scheduled_at'], name='cymed_pharm_tenant__76f067_idx')],
            },
        ),
    ]
