# Generated by Django 6.0.6 on 2026-07-07 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('set_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('dirty', 'Dirty / Awaiting Sterilization'), ('sterile', 'Sterile'), ('issued', 'Issued'), ('contaminated', 'Contaminated'), ('expired', 'Expired')], default='dirty', max_length=30)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hospital_cssd_instrument_sets',
                'ordering': ['set_code'],
            },
        ),
        migrations.CreateModel(
            name='SterilizationLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('load_number', models.CharField(max_length=50, unique=True)),
                ('sterilizer_id', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('steam', 'Steam Autoclave'), ('eto', 'Ethylene Oxide'), ('plasma', 'Hydrogen Peroxide Plasma')], max_length=30)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='loading', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('biological_indicator_result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=20)),
                ('operator_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hospital_cssd_loads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('contaminated', 'Contaminated Reported')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('logged_by', models.UUIDField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('instrument_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='cymed_hospital_cssd.instrumentset')),
            ],
            options={
                'db_table': 'cymed_hospital_cssd_tracking',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddField(
            model_name='instrumentset',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_sets', to='cymed_hospital_cssd.sterilizationload'),
        ),
    ]
