# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('processed_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_payroll_runs',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'cycom_payroll_payslips',
            },
        ),
    ]
