# Generated by Django 6.0.6 on 2026-07-05 23:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_clinical_staff',
            field=models.BooleanField(default=False, help_text='Physicians, nurses, pharmacists, techs -- anyone whose license must be tracked.'),
        ),
        migrations.CreateModel(
            name='ClinicalCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('credential_type', models.CharField(choices=[('medical_license', 'Medical License'), ('nursing_license', 'Nursing License'), ('pharmacy_license', 'Pharmacy License'), ('board_certification', 'Board Certification'), ('dea_registration', 'DEA Registration'), ('npi', 'National Provider Identifier'), ('bls_cpr', 'BLS / CPR'), ('acls', 'ACLS'), ('other', 'Other')], max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('document_ref', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='hr.employee')),
            ],
            options={
                'db_table': 'cycom_hr_clinical_credentials',
                'ordering': ['expiry_date'],
            },
        ),
    ]
