# Generated by Django 6.0.6 on 2026-07-11 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_is_clinical_staff_clinicalcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_night_shift', models.BooleanField(default=False)),
                ('differential_percent', models.DecimalField(decimal_places=2, default=0, help_text='Pay premium applied on top of base hourly rate for working this shift (e.g. 15.00 for a 15% night-shift differential). Consumed by payroll calculation.', max_digits=5)),
            ],
            options={
                'db_table': 'cycom_hr_shift_templates',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('swapped', 'Swapped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shifttemplate')),
            ],
            options={
                'db_table': 'cycom_hr_shift_assignments',
                'ordering': ['assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('covering_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_swap_requests', to='hr.employee')),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='hr.shiftassignment')),
            ],
            options={
                'db_table': 'cycom_hr_shift_swap_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['tenant_id', 'employee', 'assigned_date'], name='cycom_hr_sh_tenant__471f11_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['tenant_id', 'assigned_date'], name='cycom_hr_sh_tenant__b0d33b_idx'),
        ),
    ]
