# Generated by Django 6.0.6 on 2026-07-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_shifttemplate_shiftassignment_shiftswaprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='IBAN salary is paid to, required by WPS export.', max_length=34),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base monthly salary used to derive the hourly rate for overtime/shift-differential calculation (basic / STANDARD_MONTHLY_HOURS) and as the payslip default.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID / civil registry number, required by WPS export.', max_length=50),
        ),
    ]
