apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybercom-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  cybercom.io/environment: development

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: cybercom-backend
