# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('partner_type', models.CharField(choices=[('reseller', 'Reseller'), ('implementation', 'Implementation'), ('technology', 'Technology'), ('isv', 'ISV'), ('referral', 'Referral'), ('strategic', 'Strategic'), ('distributor', 'Distributor')], max_length=20)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('certified', 'Certified'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='prospect', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('tier', models.CharField(choices=[('registered', 'Registered'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='registered', max_length=20)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('contract_expires_at', models.DateField(blank=True, null=True)),
                ('assigned_am_id', models.UUIDField(blank=True, null=True)),
                ('certified_products', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cybercom_pe_partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('reseller', 'Reseller'), ('implementation', 'Implementation'), ('technology', 'Technology'), ('isv', 'ISV'), ('referral', 'Referral'), ('strategic', 'Strategic'), ('distributor', 'Distributor')], max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('website', models.URLField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cybercom_pe_application',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('extension_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('integration', 'Integration'), ('analytics', 'Analytics'), ('workflow', 'Workflow'), ('ui', 'UI'), ('ai', 'AI'), ('compliance', 'Compliance'), ('reporting', 'Reporting')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('price_model', models.CharField(choices=[('free', 'Free'), ('one_time', 'One Time'), ('subscription', 'Subscription'), ('usage', 'Usage Based')], default='free', max_length=20)),
                ('listing_url', models.URLField(blank=True)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_extensions', to='cybercom_partners.partner')),
            ],
            options={
                'db_table': 'cybercom_pe_marketplace_extension',
            },
        ),
        migrations.CreateModel(
            name='LeadRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('lead_name', models.CharField(max_length=200)),
                ('lead_organization', models.CharField(blank=True, max_length=200)),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_phone', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('opportunity_description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('protected_until', models.DateField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_registrations', to='cybercom_partners.partner')),
            ],
            options={
                'db_table': 'cybercom_pe_lead_registration',
            },
        ),
        migrations.CreateModel(
            name='PartnerCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_code', models.CharField(db_index=True, max_length=50)),
                ('certification_type', models.CharField(choices=[('sales', 'Sales'), ('technical', 'Technical'), ('implementation', 'Implementation'), ('architect', 'Architect'), ('support', 'Support')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='in_progress', max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('certified_consultants', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cybercom_partners.partner')),
            ],
            options={
                'db_table': 'cybercom_pe_certification',
            },
        ),
        migrations.CreateModel(
            name='PartnerPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('standard', 'Standard'), ('admin', 'Admin')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='cybercom_partners.partner')),
            ],
            options={
                'db_table': 'cybercom_pe_portal_access',
            },
        ),
    ]
