# Generated by Django 6.0.6 on 2026-07-08 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('patient_safety', 'Patient Safety'), ('clinical_effectiveness', 'Clinical Effectiveness'), ('patient_experience', 'Patient Experience'), ('efficiency', 'Efficiency')], max_length=30)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is Better'), ('lower_is_better', 'Lower is Better')], default='lower_is_better', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_hospital_quality_indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('accrediting_body', models.CharField(choices=[('jci', 'Joint Commission International (JCI)'), ('cbahi', 'Saudi Central Board for Accreditation of Healthcare Institutions (CBAHI)'), ('moh', 'Ministry of Health'), ('iso', 'ISO')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'cymed_hospital_quality_accreditation_standards',
                'ordering': ['accrediting_body', 'code'],
                'unique_together': {('tenant_id', 'accrediting_body', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceImprovementProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('phase', models.CharField(choices=[('plan', 'Plan'), ('do', 'Do'), ('study', 'Study'), ('act', 'Act'), ('closed', 'Closed')], default='plan', max_length=10)),
                ('owner_id', models.UUIDField()),
                ('started_at', models.DateField(auto_now_add=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('outcome_summary', models.TextField(blank=True)),
                ('related_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_projects', to='cymed_hospital_quality_management.qualityindicator')),
            ],
            options={
                'db_table': 'cymed_hospital_quality_pip',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant_id', 'phase'], name='cymed_hospi_tenant__2d3631_idx')],
            },
        ),
        migrations.CreateModel(
            name='QualityMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numerator', models.DecimalField(decimal_places=2, max_digits=14)),
                ('denominator', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recorded_by', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='cymed_hospital_quality_management.qualityindicator')),
            ],
            options={
                'db_table': 'cymed_hospital_quality_measurements',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['tenant_id', 'indicator', 'period_end'], name='cymed_hospi_tenant__522750_idx')],
            },
        ),
        migrations.CreateModel(
            name='StandardComplianceAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('assessed_at', models.DateField(auto_now_add=True)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], max_length=20)),
                ('assessed_by', models.UUIDField()),
                ('evidence_notes', models.TextField(blank=True)),
                ('corrective_action_due', models.DateField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cymed_hospital_quality_management.accreditationstandard')),
            ],
            options={
                'db_table': 'cymed_hospital_quality_compliance_assessments',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['tenant_id', 'compliance_status'], name='cymed_hospi_tenant__42d2fe_idx')],
            },
        ),
    ]
