# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('actor_user_id', models.UUIDField(db_index=True)),
                ('actor_role', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=200)),
                ('compliance_data', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_compliance_audit_log',
            },
        ),
        migrations.CreateModel(
            name='WorkforceComplianceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('country_code', models.CharField(choices=[('USA', 'United States'), ('SAU', 'Saudi Arabia'), ('JOR', 'Jordan'), ('ARE', 'United Arab Emirates'), ('OTHER', 'Other')], max_length=10)),
                ('region_code', models.CharField(default='ALL', max_length=20)),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=48)),
                ('max_consecutive_days', models.PositiveSmallIntegerField(default=6)),
                ('min_rest_hours_between_shifts', models.PositiveSmallIntegerField(default=11)),
                ('overtime_threshold_daily_hours', models.PositiveSmallIntegerField(default=8)),
                ('accreditation_body', models.CharField(choices=[('TJC', 'The Joint Commission (TJC)'), ('CBAHI', 'Saudi Central Board for Accrediting Healthcare Institutions (CBAHI)'), ('JCIA', 'Joint Commission International Accreditation (JCIA)'), ('DHA', 'Dubai Health Authority (DHA)'), ('DOH', 'Department of Health Abu Dhabi (DOH)'), ('OTHER', 'Other')], max_length=20)),
                ('mandatory_shift_supervisor', models.BooleanField(default=True)),
                ('credential_verification_frequency_days', models.PositiveSmallIntegerField(default=365)),
                ('ratio_overrides', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_hwm_compliance_config',
                'unique_together': {('tenant_id', 'country_code', 'region_code')},
            },
        ),
        migrations.CreateModel(
            name='WardRatioConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('ward_type', models.CharField(max_length=30)),
                ('day_ratio_nurse', models.PositiveSmallIntegerField(default=1)),
                ('day_ratio_patients', models.PositiveSmallIntegerField(default=4)),
                ('night_ratio_nurse', models.PositiveSmallIntegerField(default=1)),
                ('night_ratio_patients', models.PositiveSmallIntegerField(default=6)),
                ('compliance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_ratios', to='cymed_hwm_compliance.workforcecomplianceconfig')),
            ],
            options={
                'db_table': 'cymed_hwm_compliance_ward_ratio',
                'unique_together': {('tenant_id', 'compliance_config', 'ward_type')},
            },
        ),
        migrations.CreateModel(
            name='RamadanComplianceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('muslim_max_daily_hours', models.PositiveSmallIntegerField(default=6)),
                ('muslim_max_weekly_hours', models.PositiveSmallIntegerField(default=36)),
                ('ramadan_hijri_month', models.PositiveSmallIntegerField(default=9)),
                ('compliance_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ramadan_rule', to='cymed_hwm_compliance.workforcecomplianceconfig')),
            ],
            options={
                'db_table': 'cymed_hwm_compliance_ramadan',
                'unique_together': {('tenant_id', 'compliance_config')},
            },
        ),
    ]
