# Generated by Django 6.0.6 on 2026-07-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_pharmacy_pos', '0001_initial'),
        ('inventory', '0003_stockbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Which pharmacy this retail sale was rung up at -- lines can only draw stock from this location's own StockItem pool (see checkout()).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to='inventory.warehouse'),
        ),
    ]
