# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_area', models.CharField(choices=[('cymed', 'CyMed'), ('cycom', 'CyCom'), ('cygov', 'CyGov'), ('cycitizen', 'CyCitizen'), ('cyai', 'CyAI'), ('cyconnect', 'CyConnect'), ('platform', 'Platform'), ('all', 'All Products')], max_length=20)),
                ('target_audience', models.CharField(choices=[('end_user', 'End User'), ('administrator', 'Administrator'), ('developer', 'Developer'), ('architect', 'Architect'), ('partner', 'Partner')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('prerequisite_codes', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cybercom_acad_course',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('module_order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('lab', 'Lab'), ('webinar', 'Webinar')], max_length=20)),
                ('content_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cybercom_academy.course')),
            ],
            options={
                'db_table': 'cybercom_acad_module',
                'ordering': ['module_order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('learner_id', models.UUIDField(db_index=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_module_id', models.UUIDField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cybercom_academy.course')),
            ],
            options={
                'db_table': 'cybercom_acad_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('exam_title', models.CharField(max_length=200)),
                ('pass_score_pct', models.PositiveIntegerField(default=70)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('question_bank', models.JSONField(default=list)),
                ('is_proctored', models.BooleanField(default=False)),
                ('attempts_allowed', models.PositiveIntegerField(default=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='cybercom_academy.course')),
            ],
            options={
                'db_table': 'cybercom_acad_exam',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('learner_id', models.UUIDField(db_index=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cybercom_academy.exam')),
            ],
            options={
                'db_table': 'cybercom_acad_exam_attempt',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('learner_id', models.UUIDField(db_index=True)),
                ('certificate_type', models.CharField(choices=[('completion', 'Completion'), ('proficiency', 'Proficiency'), ('specialist', 'Specialist'), ('architect', 'Architect'), ('partner', 'Partner')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('verification_url', models.URLField(blank=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cybercom_academy.course')),
                ('exam_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='cybercom_academy.examattempt')),
            ],
            options={
                'db_table': 'cybercom_acad_certificate',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('estimated_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('badge_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='learning_paths', to='cybercom_academy.course')),
            ],
            options={
                'db_table': 'cybercom_acad_learning_path',
            },
        ),
    ]
