# Generated by Django 6.0.6 on 2026-07-05 23:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_procurement_purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('vendor_id', models.UUIDField(db_index=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending_match', 'Pending Match'), ('matched', 'Matched'), ('mismatched', 'Mismatched'), ('approved', 'Approved for Payment'), ('paid', 'Paid')], default='pending_match', max_length=20)),
                ('match_notes', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_invoices', to='cycom_procurement_purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'cycom_procurement_vendor_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity_invoiced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cycom_procurement_invoices.vendorinvoice')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='cycom_procurement_purchase_orders.poline')),
            ],
            options={
                'db_table': 'cycom_procurement_vendor_invoice_lines',
                'ordering': ['created_at'],
            },
        ),
    ]
