# Generated by Django 6.0.6 on 2026-07-08 09:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_hospital_inpatient', '0002_hospitalstay_current_code_status_codestatusorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('diet_type', models.CharField(choices=[('regular', 'Regular'), ('diabetic', 'Diabetic'), ('renal', 'Renal'), ('cardiac', 'Cardiac (Low Sodium/Fat)'), ('pureed', 'Pureed'), ('npo', 'NPO (Nothing by Mouth)'), ('clear_liquid', 'Clear Liquid'), ('full_liquid', 'Full Liquid'), ('low_sodium', 'Low Sodium'), ('gluten_free', 'Gluten Free')], max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('ordered_by', models.UUIDField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_orders', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_dietary_diet_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='MealTrayTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('prepared', 'Prepared'), ('delivered', 'Delivered'), ('refused', 'Refused by Patient')], default='scheduled', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('substitutions_notes', models.TextField(blank=True)),
                ('diet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray_tickets', to='cymed_hospital_dietary.dietorder')),
            ],
            options={
                'db_table': 'cymed_hospital_dietary_tray_tickets',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='NutritionScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('screening_date', models.DateField(auto_now_add=True)),
                ('malnutrition_risk_score', models.PositiveSmallIntegerField(help_text='MUST-style composite score')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], max_length=10)),
                ('screened_by', models.UUIDField()),
                ('referred_to_dietitian', models.BooleanField(default=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_screenings', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_dietary_nutrition_screenings',
                'ordering': ['-screening_date'],
            },
        ),
        migrations.AddIndex(
            model_name='dietorder',
            index=models.Index(fields=['tenant_id', 'discontinued_at'], name='cymed_hospi_tenant__655710_idx'),
        ),
        migrations.AddIndex(
            model_name='mealtrayticket',
            index=models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__5f6365_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionscreening',
            index=models.Index(fields=['tenant_id', 'risk_level'], name='cymed_hospi_tenant__3c962c_idx'),
        ),
    ]
