# Generated by Django 6.0.6 on 2026-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_cyidentity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='platform_cyidentity.role'),
        ),
    ]
