# Generated by Django 6.0.6 on 2026-07-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingassessment',
            name='ambulatory_aid',
            field=models.CharField(choices=[('none_bedrest_assist', 'None / Bed Rest / Nurse Assist'), ('crutches_cane_walker', 'Crutches / Cane / Walker'), ('furniture', 'Furniture')], default='none_bedrest_assist', max_length=30),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_activity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_friction_shear',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_mobility',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_moisture',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_nutrition',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='braden_sensory_perception',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='fall_risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='gait',
            field=models.CharField(choices=[('normal_bedrest_wheelchair', 'Normal / Bed Rest / Wheelchair'), ('weak', 'Weak'), ('impaired', 'Impaired')], default='normal_bedrest_wheelchair', max_length=30),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='history_of_falling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='iv_therapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='mental_status',
            field=models.CharField(choices=[('oriented_to_own_ability', 'Oriented to Own Ability'), ('forgets_limitations', 'Forgets Limitations')], default='oriented_to_own_ability', max_length=30),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='morse_fall_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='pressure_injury_risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nursingassessment',
            name='secondary_diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nursingassessment',
            name='nursing_summary',
            field=models.TextField(blank=True),
        ),
    ]
