# Generated by Django 6.0.6 on 2026-07-07 06:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('location', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('routine', 'Routine Cleaning'), ('terminal', 'Terminal Cleaning'), ('deep_clean', 'Deep Clean'), ('spill_response', 'Spill Response')], default='routine', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('assigned_to', models.UUIDField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hospital_housekeeping_tasks',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='HygieneAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('location', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('score', models.PositiveSmallIntegerField(help_text='0-100 hygiene compliance score')),
                ('auditor_id', models.UUIDField()),
                ('findings', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hospital_housekeeping_audits',
                'ordering': ['-audit_date'],
            },
        ),
    ]
