# Generated by Django 6.0.6 on 2026-07-04 20:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_inpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstay',
            name='current_code_status',
            field=models.CharField(choices=[('full_code', 'Full Code'), ('dnr', 'Do Not Resuscitate'), ('dni', 'Do Not Intubate'), ('dnr_dni', 'DNR/DNI'), ('comfort_care', 'Comfort Care Only')], default='full_code', max_length=20),
        ),
        migrations.CreateModel(
            name='CodeStatusOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('full_code', 'Full Code'), ('dnr', 'Do Not Resuscitate'), ('dni', 'Do Not Intubate'), ('dnr_dni', 'DNR/DNI'), ('comfort_care', 'Comfort Care Only')], max_length=20)),
                ('ordered_by', models.UUIDField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('discussed_with_patient', models.BooleanField(default=False)),
                ('discussed_with_family', models.BooleanField(default=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_status_orders', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_code_status_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='IndwellingDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('device_type', models.CharField(choices=[('central_line', 'Central Line (CLABSI surveillance)'), ('foley_catheter', 'Urinary Catheter (CAUTI surveillance)'), ('arterial_line', 'Arterial Line'), ('picc', 'PICC Line (CLABSI surveillance)')], max_length=20)),
                ('insertion_site', models.CharField(blank=True, max_length=100)),
                ('inserted_at', models.DateTimeField()),
                ('inserted_by', models.UUIDField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indwelling_devices', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_indwelling_devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssociatedInfection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_by', models.UUIDField()),
                ('organism', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infections', to='cymed_hospital_inpatient.indwellingdevice')),
            ],
            options={
                'db_table': 'cymed_hospital_device_associated_infections',
            },
        ),
        migrations.CreateModel(
            name='VTEProphylaxisOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('method', models.CharField(choices=[('pharmacologic', 'Pharmacologic'), ('mechanical', 'Mechanical (SCDs/compression stockings)'), ('both', 'Pharmacologic + Mechanical'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('ordered_by', models.UUIDField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('contraindication_reason', models.TextField(blank=True)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vte_prophylaxis', to='cymed_hospital_inpatient.hospitalstay')),
            ],
            options={
                'db_table': 'cymed_hospital_vte_prophylaxis_orders',
            },
        ),
    ]
