# Generated by Django 6.0.6 on 2026-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_preauthorization', '0002_alter_authorizationappeal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorization',
            name='invoice_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='nphies_claim_bundle_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='nphies_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='nphies_response_bundle_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='nphies_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('offline', 'Offline (Queued for Retry)'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddIndex(
            model_name='preauthorization',
            index=models.Index(fields=['tenant_id', 'invoice_id'], name='cymed_rcm_p_tenant__4a44d8_idx'),
        ),
    ]
