# Generated by Django 6.0.6 on 2026-07-08 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RehabReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('discipline', models.CharField(choices=[('physical_therapy', 'Physical Therapy'), ('occupational_therapy', 'Occupational Therapy'), ('speech_therapy', 'Speech Therapy')], max_length=30)),
                ('referring_provider_id', models.UUIDField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('referred_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'cymed_hospital_rehab_referrals',
                'ordering': ['-referred_at'],
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='cymed_hospi_tenant__288aa2_idx'), models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__314a2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('goals', models.TextField()),
                ('frequency_per_week', models.PositiveSmallIntegerField(default=3)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=6)),
                ('therapist_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='cymed_hospital_rehabilitation.rehabreferral')),
            ],
            options={
                'db_table': 'cymed_hospital_rehab_treatment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('session_date', models.DateField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('therapist_id', models.UUIDField()),
                ('activities', models.TextField()),
                ('patient_response', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cymed_hospital_rehabilitation.treatmentplan')),
            ],
            options={
                'db_table': 'cymed_hospital_rehab_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('measured_at', models.DateField(auto_now_add=True)),
                ('measure_type', models.CharField(choices=[('fim', 'Functional Independence Measure (FIM)'), ('rom', 'Range of Motion'), ('pain_scale', 'Pain Scale (0-10)'), ('gait_speed', 'Gait Speed'), ('mmse', 'Mini-Mental State Examination')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_measurements', to='cymed_hospital_rehabilitation.treatmentplan')),
            ],
            options={
                'db_table': 'cymed_hospital_rehab_outcome_measurements',
                'ordering': ['-measured_at'],
            },
        ),
    ]
