# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('deployment_code', models.CharField(max_length=50, unique=True)),
                ('deployment_type', models.CharField(choices=[('cloud', 'Cloud (SaaS)'), ('private_cloud', 'Private Cloud'), ('government_cloud', 'Government Cloud'), ('on_premises', 'On-Premises'), ('hybrid', 'Hybrid'), ('air_gapped', 'Air-Gapped')], max_length=30)),
                ('tenancy_model', models.CharField(choices=[('single_tenant', 'Single Tenant'), ('multi_tenant', 'Multi-Tenant')], default='single_tenant', max_length=20)),
                ('infrastructure', models.CharField(choices=[('kubernetes', 'Kubernetes'), ('docker_compose', 'Docker Compose'), ('aws_ecs', 'AWS ECS'), ('aws_eks', 'AWS EKS'), ('azure_aks', 'Azure AKS'), ('gcp_gke', 'GCP GKE'), ('oracle_oke', 'Oracle OKE'), ('vmware', 'VMware vSphere'), ('bare_metal', 'Bare Metal')], max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('validating', 'Validating Environment'), ('provisioning', 'Provisioning'), ('installing', 'Installing'), ('configuring', 'Configuring'), ('testing', 'Testing'), ('go_live', 'Go-Live'), ('live', 'Live'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('platform_version', models.CharField(blank=True, max_length=50)),
                ('licensed_products', models.JSONField(default=list)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('assigned_engineer_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cybercom_deploy_record',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('snapshot', 'Snapshot')], max_length=20)),
                ('storage_location', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.PositiveSmallIntegerField(default=30)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_backup',
            },
        ),
        migrations.CreateModel(
            name='DeploymentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('step_name', models.CharField(max_length=200)),
                ('step_category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_log', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_step',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('check_name', models.CharField(max_length=200)),
                ('check_category', models.CharField(max_length=50)),
                ('passed', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_checks', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_env_check',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('overall_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('component_statuses', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_health_snapshot',
            },
        ),
        migrations.CreateModel(
            name='TenantProvision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('tenant_name', models.CharField(max_length=200)),
                ('tenant_slug', models.CharField(max_length=100)),
                ('platform_tenant_id', models.UUIDField(blank=True, null=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('edition', models.CharField(max_length=50)),
                ('country_config', models.CharField(default='USA', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('license_key', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_provisions', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_tenant_provision',
            },
        ),
        migrations.CreateModel(
            name='UpgradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('from_version', models.CharField(max_length=50)),
                ('to_version', models.CharField(max_length=50)),
                ('upgrade_type', models.CharField(choices=[('patch', 'Patch'), ('minor', 'Minor'), ('major', 'Major')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_available', models.BooleanField(default=True)),
                ('upgrade_notes', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='cybercom_deployment.deploymentrecord')),
            ],
            options={
                'db_table': 'cybercom_deploy_upgrade',
            },
        ),
    ]
