# Generated by Django 6.0.6 on 2026-07-05 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_pharmacy_interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosingGuideline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('drug_code', models.CharField(db_index=True, max_length=100)),
                ('drug_name', models.CharField(max_length=500)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('dose_unit', models.CharField(max_length=50)),
                ('min_single_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_single_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_daily_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('weight_based', models.BooleanField(default=False)),
                ('max_dose_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_rx_dosing_guidelines',
            },
        ),
        migrations.CreateModel(
            name='DoseRangeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('medication_order_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('drug_code', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=500)),
                ('ordered_dose', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ordered_dose_unit', models.CharField(max_length=50)),
                ('issue', models.CharField(choices=[('below_min', 'Below Minimum Single Dose'), ('above_max', 'Above Maximum Single Dose'), ('above_max_daily', 'Above Maximum Daily Dose'), ('above_weight_based_max', 'Above Weight-Based Maximum')], max_length=30)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('guideline_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('overridden', 'Overridden')], default='open', max_length=20)),
                ('overridden_by', models.UUIDField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('guideline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cymed_pharmacy_interactions.dosingguideline')),
            ],
            options={
                'db_table': 'cymed_rx_dose_range_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
