#!/bin/bash

# =============================================================
# CyberCom Platform — Automated Deployment Script
# Deploys to OCI VM (158.178.130.4)
# =============================================================

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
IMAGE_TAG="${1:-latest}"
DATABASE_URL="${2}"
REDIS_URL="${3}"
JWT_SECRET="${4}"
POSTGRES_PASSWORD="${5}"
REDIS_PASSWORD="${6}"
OCI_TENANCY_OCID="${7}"
ALLOWED_HOSTS="${8:-api.cy-com.com,localhost}"

DEPLOY_DIR="/opt/cybercom/platform"
APP_DIR="${DEPLOY_DIR}/app"
ENV_FILE="${DEPLOY_DIR}/.env"

# Logging functions
log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

success() {
    echo -e "${GREEN}✓${NC} $1"
}

error() {
    echo -e "${RED}✗${NC} $1" >&2
}

warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Validation
log "Starting deployment..."
log "Image Tag: ${IMAGE_TAG}"

if [ -z "$DATABASE_URL" ]; then
    error "DATABASE_URL not provided"
    exit 1
fi

if [ -z "$JWT_SECRET" ]; then
    error "JWT_SECRET not provided"
    exit 1
fi

success "Configuration validated"

# Create directories
log "Setting up directories..."
sudo mkdir -p "${APP_DIR}"
sudo chown ubuntu:ubuntu "${DEPLOY_DIR}"
success "Directories ready"

# Prepare .env file
log "Generating .env file..."
cat > "${ENV_FILE}" << EOF
# Auto-generated by CI/CD pipeline
# Generated: $(date)

IMAGE_TAG=${IMAGE_TAG}
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
OCI_TENANCY_OCID=${OCI_TENANCY_OCID}
ALLOWED_HOSTS=${ALLOWED_HOSTS}
ENVIRONMENT=production
LOG_LEVEL=INFO

# PostgreSQL
POSTGRES_DB=cybercom
POSTGRES_USER=cybercom

# Application
DEBUG=false
EOF

chmod 600 "${ENV_FILE}"
success ".env file created"

# Move deploy artifacts
log "Copying application files..."
cp -r /tmp/cybercom-deploy/docker-compose.yml "${DEPLOY_DIR}/"
cp -r /tmp/cybercom-deploy/infrastructure "${DEPLOY_DIR}/"
cp -r /tmp/cybercom-deploy/backend "${DEPLOY_DIR}/"
success "Files copied"

# Stop existing containers
log "Stopping existing containers..."
cd "${DEPLOY_DIR}"
docker-compose -f docker-compose.yml down --remove-orphans 2>/dev/null || true
success "Containers stopped"

# Pull latest base images
log "Pulling base images..."
docker pull postgres:16-alpine
docker pull redis:7-alpine
docker pull nginx:1.27-alpine
success "Base images updated"

# Build and start services
log "Building and starting services..."
docker-compose -f docker-compose.yml up --build -d

# Wait for services to be healthy
log "Waiting for services to become healthy..."
RETRIES=0
MAX_RETRIES=30

while [ $RETRIES -lt $MAX_RETRIES ]; do
    if docker-compose -f docker-compose.yml ps | grep -q "cybercom-api.*healthy"; then
        success "API service is healthy"
        break
    fi
    RETRIES=$((RETRIES + 1))
    echo -n "."
    sleep 2
done

if [ $RETRIES -eq $MAX_RETRIES ]; then
    error "Services did not become healthy in time"
    docker-compose -f docker-compose.yml logs api
    exit 1
fi

# Run database migrations (if applicable)
log "Running database migrations..."
docker-compose -f docker-compose.yml exec -T api python manage.py migrate --noinput 2>/dev/null || warning "Migrations skipped (command may not apply)"
success "Migrations completed"

# Collect static files (if applicable)
log "Collecting static files..."
docker-compose -f docker-compose.yml exec -T api python manage.py collectstatic --noinput 2>/dev/null || warning "Static files collection skipped"
success "Static files prepared"

# Verify Nginx configuration
log "Validating Nginx configuration..."
sudo nginx -t > /dev/null 2>&1
success "Nginx configuration valid"

# Reload Nginx
log "Reloading Nginx..."
sudo systemctl reload nginx
success "Nginx reloaded"

# Health checks
log "Running health checks..."
HEALTH_CHECK_RETRIES=0
MAX_HEALTH_CHECKS=5

while [ $HEALTH_CHECK_RETRIES -lt $MAX_HEALTH_CHECKS ]; do
    if curl -sf http://localhost:8000/health > /dev/null; then
        success "Health check passed"
        break
    fi
    HEALTH_CHECK_RETRIES=$((HEALTH_CHECK_RETRIES + 1))
    echo -n "."
    sleep 2
done

if [ $HEALTH_CHECK_RETRIES -eq $MAX_HEALTH_CHECKS ]; then
    warning "Health check endpoint not responding"
fi

# Display service status
log "Service status:"
docker-compose -f docker-compose.yml ps

# Cleanup
log "Cleaning up temporary files..."
rm -rf /tmp/cybercom-deploy

# Generate deployment report
log "Deployment Summary"
echo "===================="
echo "✓ Image Tag: ${IMAGE_TAG}"
echo "✓ Deployment Directory: ${DEPLOY_DIR}"
echo "✓ Timestamp: $(date)"
echo "✓ Services Running:"
docker-compose -f docker-compose.yml ps --services --filter status=running | sed 's/^/  - /'
echo ""
echo "Available domains:"
echo "  - https://api.cy-com.com"
echo "  - https://cy-com.com"
echo "  - https://health.cy-com.com"
echo "  - https://provider.cy-com.com"
echo "  - https://hospital.cy-com.com"
echo "  - https://clinic.cy-com.com"
echo "  - https://lab.cy-com.com"
echo "  - https://imaging.cy-com.com"
echo "  - https://pharmacy.cy-com.com"
echo "  - https://portal.cy-com.com"
echo "  - https://partners.cy-com.com"
echo "  - https://docs.cy-com.com"
echo ""
echo "Logs:"
echo "  docker-compose -f ${DEPLOY_DIR}/docker-compose.yml logs -f api"
echo "  docker-compose -f ${DEPLOY_DIR}/docker-compose.yml logs -f nginx"
echo ""

success "Deployment completed successfully!"
