# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('workforce_profile_id', models.UUIDField(db_index=True)),
                ('call_mode', models.CharField(choices=[('in_house', 'In-House (< 5 min response)'), ('home_call', 'Home Call (< 30 min response)'), ('emergency', 'Emergency Call')], max_length=20)),
                ('call_tier', models.CharField(choices=[('primary', 'Primary (First Responder)'), ('secondary', 'Secondary (Backup)'), ('backup', 'Backup (Tertiary)')], max_length=20)),
                ('call_seniority', models.CharField(choices=[('resident', 'Resident Call'), ('consultant', 'Consultant Call'), ('emergency', 'Emergency Activation')], max_length=20)),
                ('response_sla_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_hwm_oncall_assignment',
            },
        ),
        migrations.CreateModel(
            name='OnCallPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('initiating_ward_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergent', 'Emergent'), ('critical', 'Critical')], default='urgent', max_length=20)),
                ('clinical_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('missed', 'Missed')], default='sent', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_id', models.UUIDField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_oncall_page',
            },
        ),
        migrations.CreateModel(
            name='OnCallRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('specialty', models.CharField(max_length=100)),
                ('roster_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('published_by_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_oncall_roster',
            },
        ),
        migrations.CreateModel(
            name='CallSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('requester_profile_id', models.UUIDField(db_index=True)),
                ('recipient_profile_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('approver_role', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('policy_cache_updated', models.BooleanField(default=False)),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests', to='cymed_hwm_oncall.oncallassignment')),
            ],
            options={
                'db_table': 'cymed_hwm_oncall_call_swap',
            },
        ),
        migrations.CreateModel(
            name='OnCallEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('escalation_level', models.PositiveSmallIntegerField()),
                ('escalated_to_profile_id', models.UUIDField(db_index=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('department_chair_alerted', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='cymed_hwm_oncall.oncallpage')),
            ],
            options={
                'db_table': 'cymed_hwm_oncall_escalation',
            },
        ),
        migrations.AddField(
            model_name='oncallpage',
            name='oncall_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='cymed_hwm_oncall.oncallroster'),
        ),
        migrations.AddField(
            model_name='oncallassignment',
            name='oncall_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cymed_hwm_oncall.oncallroster'),
        ),
        migrations.AlterUniqueTogether(
            name='oncallassignment',
            unique_together={('tenant_id', 'oncall_roster', 'call_tier')},
        ),
    ]
