# Generated by Django 6.0.6 on 2026-07-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_pharmacy_dispensing', '0001_initial'),
        ('inventory', '0003_stockbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenseorder',
            name='pharmacy_location',
            field=models.ForeignKey(blank=True, help_text="Which pharmacy stock pool this order is fulfilled from (e.g. ER pharmacy vs outpatient retail pharmacy) -- was free text, now a real Warehouse so stock can't be double-counted or dispensed from the wrong location's pool.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispense_orders', to='inventory.warehouse'),
        ),
    ]
