apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybercom

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  cybercom.io/environment: base
