# Generated by Django 6.0.6 on 2026-07-11 20:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_facilities', '0002_room_accommodation_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialysisMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('last_serviced_at', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_machines', to='cymed_facilities.room')),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_machines',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='DialysisOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('modality', models.CharField(choices=[('hemodialysis', 'Hemodialysis'), ('peritoneal_dialysis', 'Peritoneal Dialysis')], max_length=30)),
                ('referring_provider_id', models.UUIDField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('ordered_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_orders',
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='cymed_hospi_tenant__68c382_idx'), models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__b14340_idx')],
            },
        ),
        migrations.CreateModel(
            name='DialysisCarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('frequency_per_week', models.PositiveSmallIntegerField(default=3)),
                ('session_duration_hours', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('dry_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dialyzer_type', models.CharField(blank=True, max_length=100)),
                ('nephrologist_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='cymed_hospital_dialysis.dialysisorder')),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_care_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('technician_id', models.UUIDField()),
                ('session_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pre_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fluid_removed_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pre_bp_sys', models.PositiveIntegerField()),
                ('pre_bp_dia', models.PositiveIntegerField()),
                ('post_bp_sys', models.PositiveIntegerField(blank=True, null=True)),
                ('post_bp_dia', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_flow_rate_ml_min', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cymed_hospital_dialysis.dialysismachine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cymed_hospital_dialysis.dialysiscareplan')),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_sessions',
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DialysisComplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('complication_type', models.CharField(choices=[('hypotension', 'Intradialytic Hypotension'), ('cramping', 'Muscle Cramping'), ('access_clotting', 'Access Clotting'), ('access_infection', 'Access Infection'), ('bleeding', 'Bleeding'), ('chest_pain', 'Chest Pain'), ('nausea_vomiting', 'Nausea/Vomiting'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20)),
                ('action_taken', models.TextField()),
                ('reported_by_id', models.UUIDField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='cymed_hospital_dialysis.dialysissession')),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_complications',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='VascularAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('access_type', models.CharField(choices=[('av_fistula', 'AV Fistula'), ('av_graft', 'AV Graft'), ('central_catheter', 'Central Venous Catheter'), ('peritoneal_catheter', 'Peritoneal Catheter')], max_length=30)),
                ('site', models.CharField(max_length=100)),
                ('placed_by_provider_id', models.UUIDField()),
                ('placed_at', models.DateField()),
                ('status', models.CharField(choices=[('maturing', 'Maturing'), ('active', 'Active'), ('failed', 'Failed'), ('removed', 'Removed')], default='maturing', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_hospital_dialysis_vascular_access',
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='cymed_hospi_tenant__98cbce_idx'), models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__353a38_idx')],
            },
        ),
        migrations.AddField(
            model_name='dialysiscareplan',
            name='vascular_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to='cymed_hospital_dialysis.vascularaccess'),
        ),
        migrations.AddIndex(
            model_name='dialysissession',
            index=models.Index(fields=['tenant_id', 'plan', 'session_date'], name='cymed_hospi_tenant__98b334_idx'),
        ),
    ]
