# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('roster_cycle_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning')], max_length=10)),
                ('issues', models.JSONField(default=list)),
                ('slots_checked', models.PositiveIntegerField(default=0)),
                ('slots_failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_hwm_acuity_validation_run',
            },
        ),
        migrations.CreateModel(
            name='PatientAcuityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('ward_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('acuity_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 — Stable (HPPD 4.0h)'), (2, 'Level 2 — Moderate Care (HPPD 6.5h)'), (3, 'Level 3 — High Dependency (HPPD 9.5h)'), (4, 'Level 4 — Intensive Care (HPPD 18.0-24.0h)')])),
                ('news2_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hppd_target', models.DecimalField(decimal_places=1, max_digits=5)),
                ('scored_at', models.DateTimeField()),
                ('scored_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hwm_acuity_patient_score',
            },
        ),
        migrations.CreateModel(
            name='SkillMixValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('roster_cycle_id', models.UUIDField(db_index=True)),
                ('ward_id', models.UUIDField(db_index=True)),
                ('slot_date', models.DateField()),
                ('shift_type', models.CharField(max_length=20)),
                ('charge_nurse_present', models.BooleanField(default=False)),
                ('total_nurses_scheduled', models.PositiveSmallIntegerField(default=0)),
                ('senior_nurse_count', models.PositiveSmallIntegerField(default=0)),
                ('senior_nurse_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('specialty_cert_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('failure_reasons', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cymed_hwm_acuity_skill_mix',
            },
        ),
        migrations.CreateModel(
            name='WardCoverageRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('facility_id', models.UUIDField(db_index=True)),
                ('ward_type', models.CharField(choices=[('icu', 'Intensive Care Unit (ICU)'), ('nicu', 'Neonatal ICU (NICU)'), ('ed', 'Emergency Department (ED)'), ('ld', 'Labor & Delivery (L&D)'), ('pediatrics', 'Pediatrics'), ('med_surg', 'Medical-Surgical'), ('or', 'Operating Room'), ('general', 'General')], max_length=20)),
                ('day_ratio_nurse', models.PositiveSmallIntegerField(default=1)),
                ('day_ratio_patients', models.PositiveSmallIntegerField(default=4)),
                ('night_ratio_nurse', models.PositiveSmallIntegerField(default=1)),
                ('night_ratio_patients', models.PositiveSmallIntegerField(default=6)),
                ('min_physician_on_site', models.PositiveSmallIntegerField(default=1)),
                ('physician_coverage_24_7', models.BooleanField(default=False)),
                ('min_senior_nurse_pct', models.PositiveSmallIntegerField(default=30)),
                ('specialty_cert_required_100pct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hwm_acuity_coverage_req',
                'unique_together': {('tenant_id', 'facility_id', 'ward_type')},
            },
        ),
    ]
