# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('demo_type', models.CharField(choices=[('full_platform', 'Full Platform Demo'), ('cymed_hospital', 'CyMed Hospital Edition'), ('cymed_clinic', 'CyMed Clinic Edition'), ('cymed_lab', 'CyMed Laboratory Edition'), ('cymed_imaging', 'CyMed Imaging Edition'), ('cymed_pharmacy', 'CyMed Pharmacy Edition'), ('cymed_patient_portal', 'CyMed Patient Portal'), ('cymed_provider_portal', 'CyMed Provider Portal'), ('rcm', 'Revenue Cycle Management'), ('population_health', 'Population Health'), ('workforce', 'Workforce Management'), ('cycom_erp', 'CyCom ERP'), ('cygov', 'CyGov Government Platform'), ('cycitizen', 'CyCitizen Services'), ('cyai', 'CyAI Platform')], max_length=40)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('paused', 'Paused'), ('resetting', 'Resetting'), ('expired', 'Expired'), ('archived', 'Archived')], default='provisioning', max_length=20)),
                ('prospect_name', models.CharField(blank=True, max_length=200)),
                ('prospect_organization', models.CharField(blank=True, max_length=200)),
                ('prospect_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_ae_id', models.UUIDField(blank=True, null=True)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('admin_username', models.CharField(blank=True, max_length=100)),
                ('admin_password_hash', models.CharField(blank=True, max_length=200)),
                ('product_edition', models.CharField(default='enterprise', max_length=50)),
                ('country_config', models.CharField(default='USA', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('reset_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'cybercom_demo_environment',
            },
        ),
        migrations.CreateModel(
            name='ProductTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_code', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('tour_steps', models.JSONField(default=list)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cybercom_demo_product_tour',
            },
        ),
        migrations.CreateModel(
            name='DemoResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('requested_by_id', models.UUIDField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_requests', to='cybercom_demo.demoenvironment')),
            ],
            options={
                'db_table': 'cybercom_demo_reset_request',
            },
        ),
        migrations.CreateModel(
            name='DemoScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('scenario_type', models.CharField(choices=[('patient_admission', 'Patient Admission Flow'), ('emergency_triage', 'Emergency Department Triage'), ('surgical_workflow', 'Surgical Workflow'), ('lab_order_result', 'Lab Order to Result'), ('imaging_workflow', 'Imaging Workflow'), ('pharmacy_dispensing', 'Pharmacy Dispensing'), ('patient_portal_journey', 'Patient Portal Journey'), ('provider_portal_workflow', 'Provider Portal Workflow'), ('rcm_claims_cycle', 'RCM Claims Cycle'), ('ai_clinical_decision', 'AI Clinical Decision Support'), ('government_citizen', 'Government Citizen Services'), ('workforce_scheduling', 'Workforce Scheduling'), ('custom', 'Custom Scenario')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_count', models.PositiveSmallIntegerField(default=0)),
                ('steps', models.JSONField(default=list)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_interactive', models.BooleanField(default=True)),
                ('ai_narration_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='cybercom_demo.demoenvironment')),
            ],
            options={
                'db_table': 'cybercom_demo_scenario',
            },
        ),
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('presenter_id', models.UUIDField(blank=True, null=True)),
                ('attendee_names', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('steps_completed', models.PositiveSmallIntegerField(default=0)),
                ('feedback_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('follow_up_action', models.CharField(blank=True, max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cybercom_demo.demoenvironment')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cybercom_demo.demoscenario')),
            ],
            options={
                'db_table': 'cybercom_demo_session',
            },
        ),
        migrations.CreateModel(
            name='DemoTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('tenant_name', models.CharField(max_length=200)),
                ('tenant_type', models.CharField(max_length=50)),
                ('platform_tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('seed_dataset', models.CharField(default='standard', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='cybercom_demo.demoenvironment')),
            ],
            options={
                'db_table': 'cybercom_demo_tenant',
            },
        ),
    ]
