# Generated by Django 6.0.6 on 2026-07-08 09:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('source_ward', models.CharField(max_length=100)),
                ('item_count_collected', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('collected_by', models.UUIDField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_laundry_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('item_count_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('at_laundry', 'At Laundry'), ('returned', 'Returned'), ('short_count_flagged', 'Short Count Flagged')], default='collected', max_length=20)),
            ],
            options={
                'db_table': 'cymed_hospital_linen_laundry_batches',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__37768c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinenCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('ward', models.CharField(max_length=100)),
                ('cart_type', models.CharField(choices=[('clean', 'Clean Linen'), ('soiled', 'Soiled Linen')], max_length=10)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('par_level', models.PositiveIntegerField(default=0, help_text='Target stock level for clean carts; capacity threshold for soiled carts.')),
            ],
            options={
                'db_table': 'cymed_hospital_linen_carts',
                'ordering': ['ward', 'cart_type'],
                'unique_together': {('tenant_id', 'ward', 'cart_type')},
            },
        ),
    ]
