# Generated by Django 6.0.6 on 2026-07-05 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='par_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Target stock level to replenish up to when a reorder is triggered.', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='preferred_vendor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Reorder is triggered when quantity falls to or below this level. 0 disables auto-reorder.', max_digits=12),
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_at_trigger', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reorder_level_at_trigger', models.DecimalField(decimal_places=3, max_digits=12)),
                ('suggested_order_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('requisitioned', 'Requisitioned'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('requisition_id', models.UUIDField(blank=True, null=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'cycom_inventory_reorder_alerts',
            },
        ),
    ]
