# Generated by Django 6.0.6 on 2026-07-07 19:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_par_level_stockitem_preferred_vendor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(auto_now_add=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'cycom_inventory_stock_batches',
                'ordering': ['expiry_date'],
                'unique_together': {('stock_item', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Required for batch-tracked (medical/pharmacy) items on receipt/issue; left null for non-batch-tracked general inventory.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch'),
        ),
    ]
