# Generated by Django 6.0.6 on 2026-07-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_facilities', '0002_room_accommodation_tier'),
        ('inventory', '0003_stockbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Physical room this warehouse/stock pool is located in, e.g. a specific pharmacy counter -- lets multiple warehouses (ER pharmacy vs outpatient retail pharmacy) be distinguished by real facility location, not just free-text.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='cymed_facilities.room'),
        ),
    ]
