# Generated by Django 6.0.6 on 2026-07-05 22:09

import platform.common.security.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='city',
            field=platform.common.security.encryption.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='line1',
            field=platform.common.security.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='line2',
            field=platform.common.security.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='postal_code',
            field=platform.common.security.encryption.EncryptedCharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='telecom_value',
            field=platform.common.security.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientemergencycontact',
            name='email',
            field=platform.common.security.encryption.EncryptedEmailField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='patientemergencycontact',
            name='name',
            field=platform.common.security.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientemergencycontact',
            name='phone',
            field=platform.common.security.encryption.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patientrelationship',
            name='address',
            field=platform.common.security.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientrelationship',
            name='related_person_name',
            field=platform.common.security.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientrelationship',
            name='telecom',
            field=platform.common.security.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
