# Generated by Django 6.0.6 on 2026-07-07 12:32

import django.utils.timezone
import platform.common.security.encryption
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantComplianceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('jofotara_enabled', models.BooleanField(default=False)),
                ('jofotara_tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('jofotara_activity_code', models.CharField(blank=True, max_length=50)),
                ('jofotara_client_secret', platform.common.security.encryption.EncryptedCharField(blank=True, max_length=255)),
                ('zatca_enabled', models.BooleanField(default=False)),
                ('zatca_csid', platform.common.security.encryption.EncryptedTextField(blank=True)),
                ('zatca_production_csid', platform.common.security.encryption.EncryptedTextField(blank=True)),
                ('zatca_onboarding_otp', platform.common.security.encryption.EncryptedCharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'tenant compliance settings',
                'db_table': 'cymed_commercial_tenant_compliance_settings',
                'unique_together': {('tenant_id',)},
            },
        ),
    ]
