# Generated by Django 6.0.6 on 2026-07-07 20:11

import platform.common.security.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_compliance_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompliancesettings',
            name='nphies_client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenantcompliancesettings',
            name='nphies_client_secret',
            field=platform.common.security.encryption.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantcompliancesettings',
            name='nphies_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantcompliancesettings',
            name='nphies_provider_license',
            field=models.CharField(blank=True, help_text="Facility's CCHI/NPHIES-issued provider license number.", max_length=50),
        ),
    ]
