# Generated by Django 6.0.6 on 2026-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_compliance_settings', '0002_tenantcompliancesettings_nphies_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompliancesettings',
            name='jofotara_client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
