# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('requester_profile_id', models.UUIDField(db_index=True)),
                ('recipient_profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('requester_slot_id', models.UUIDField(db_index=True)),
                ('recipient_slot_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending_recipient', 'Pending Recipient Acceptance'), ('pending_validation', 'Pending Validation'), ('pending_approval', 'Pending Supervisor Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('committed', 'Committed')], default='pending_recipient', max_length=30)),
                ('rejection_reason', models.CharField(blank=True, choices=[('fatigue_violation', 'Fatigue Constraint Violation'), ('credential_mismatch', 'Credential Mismatch'), ('duty_hour_violation', 'Duty Hour Violation'), ('rest_period_violation', 'Rest Period Violation'), ('supervisor_rejected', 'Supervisor Rejected'), ('recipient_declined', 'Recipient Declined'), ('other', 'Other')], max_length=40)),
                ('rejection_detail', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_responded_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_cache_updated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hwm_swaps_request',
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('approver_id', models.UUIDField(db_index=True)),
                ('approver_role', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('swap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='cymed_hwm_swaps.shiftswaprequest')),
            ],
            options={
                'db_table': 'cymed_hwm_swaps_approval',
            },
        ),
        migrations.CreateModel(
            name='SwapValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('check_type', models.CharField(max_length=50)),
                ('passed', models.BooleanField()),
                ('detail', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('swap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='cymed_hwm_swaps.shiftswaprequest')),
            ],
            options={
                'db_table': 'cymed_hwm_swaps_validation_log',
            },
        ),
    ]
