# Generated by Django 6.0.6 on 2026-07-08 09:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=300)),
                ('principal_investigator_id', models.UUIDField()),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('protocol_number', models.CharField(max_length=100)),
                ('irb_approval_number', models.CharField(blank=True, max_length=100)),
                ('irb_status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='submitted', max_length=20)),
                ('irb_approval_date', models.DateField(blank=True, null=True)),
                ('irb_expiry_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('phase_1', 'Phase I'), ('phase_2', 'Phase II'), ('phase_3', 'Phase III'), ('phase_4', 'Phase IV'), ('observational', 'Observational'), ('retrospective', 'Retrospective Chart Review')], max_length=20)),
                ('target_enrollment', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hospital_research_protocols',
                'ordering': ['-irb_approval_date'],
                'indexes': [models.Index(fields=['tenant_id', 'irb_status'], name='cymed_hospi_tenant__b1ae63_idx')],
                'unique_together': {('tenant_id', 'protocol_number')},
            },
        ),
        migrations.CreateModel(
            name='StudyEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('screening', 'Screening'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('screen_failed', 'Screen Failed')], default='screening', max_length=20)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('consented_by', models.UUIDField(blank=True, null=True)),
                ('enrolled_at', models.DateField(blank=True, null=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cymed_hospital_research.researchprotocol')),
            ],
            options={
                'db_table': 'cymed_hospital_research_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAdverseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening'), ('fatal', 'Fatal')], max_length=20)),
                ('related_to_study', models.BooleanField(help_text='Investigator assessment of causality to the study intervention.')),
                ('reported_to_irb', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.UUIDField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='cymed_hospital_research.studyenrollment')),
            ],
            options={
                'db_table': 'cymed_hospital_research_adverse_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='studyenrollment',
            index=models.Index(fields=['tenant_id', 'patient_id'], name='cymed_hospi_tenant__d35667_idx'),
        ),
        migrations.AddIndex(
            model_name='studyenrollment',
            index=models.Index(fields=['tenant_id', 'status'], name='cymed_hospi_tenant__fb58b6_idx'),
        ),
        migrations.AddIndex(
            model_name='researchadverseevent',
            index=models.Index(fields=['tenant_id', 'severity'], name='cymed_hospi_tenant__a9f2a7_idx'),
        ),
    ]
