# Generated by Django 6.0.6 on 2026-07-08 09:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomedicalEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('calibration_due', 'Calibration Due'), ('under_repair', 'Under Repair'), ('out_of_service', 'Out of Service'), ('decommissioned', 'Decommissioned')], default='in_service', max_length=20)),
                ('calibration_interval_days', models.PositiveIntegerField(default=365)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_due', models.DateField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biomedical_detail', to='assets.asset')),
            ],
            options={
                'db_table': 'cycom_assets_biomedical_equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('service_type', models.CharField(choices=[('calibration', 'Calibration'), ('preventive_maintenance', 'Preventive Maintenance'), ('repair', 'Repair'), ('safety_inspection', 'Safety Inspection')], max_length=30)),
                ('service_date', models.DateField()),
                ('performed_by', models.CharField(max_length=200)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='assets.biomedicalequipment')),
            ],
            options={
                'db_table': 'cycom_assets_equipment_service_records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='biomedicalequipment',
            index=models.Index(fields=['tenant_id', 'status'], name='cycom_asset_tenant__181fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='biomedicalequipment',
            index=models.Index(fields=['tenant_id', 'next_calibration_due'], name='cycom_asset_tenant__db3883_idx'),
        ),
    ]
